#!/bin/bash

JAVA_PLATE="import java.util.*;

public class Plate{

    public static void main(String[] args){
        Scanner in = new Scanner(System.in);
        int testCases = Integer.parseInt(in.nextLine());
        for(int t = 0; t < testCases; t++){
            int[] abArr = klinUtil.sArrToIArr(in.nextLine().split(\" \"));
            //insert code
        }
    }
    
}


class klinUtil {
    public static int[] sArrToIArr(String[] sArr){
        int[] iArr = new int[sArr.length];
        for(int i = 0; i < sArr.length; i++){
            iArr[i] = Integer.parseInt(sArr[i]);
        }
        return iArr;
    }
}
"

if [ -z "$1" ]
then
    echo "usage: klinCompetitiveBoil Classname"
else
    echo "$JAVA_PLATE" | sed s/Plate/$1/ > $1.java
    echo "boilerplate for $1.java has been created"
fi
